#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace PollSystem.OpenAccess.Identity	
{
	public partial class PollSystemDbCotnext : OpenAccessContext, IIdentityModelUnitOfWork
	{
        private static string connectionStringName = @"OracleIdentityConnection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = new IdentityModelMetadataSource();
		
		public PollSystemDbCotnext()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public PollSystemDbCotnext(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public PollSystemDbCotnext(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public PollSystemDbCotnext(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public PollSystemDbCotnext(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "Oracle";
			backend.ProviderName = "Oracle.DataAccess.Client";
			return backend;
		}

        public IQueryable<IdentityUser> IdentityUsers
        {
            get
            {
                return this.GetAll<IdentityUser>();
            }
        }

        public IQueryable<IdentityRole> IdentityRoles
        {
            get
            {
                return this.GetAll<IdentityRole>();
            }
        }

        public IQueryable<Question> Questions
        {
            get
            {
                return this.GetAll<Question>();
            }
        }

        public IQueryable<Answer> Answers
        {
            get
            {
                return this.GetAll<Answer>();
            }
        }
	}
	
	public interface IIdentityModelUnitOfWork : IUnitOfWork
	{
	}
}
#pragma warning restore 1591
